name: Backend CI/CD

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  backend-build:
    runs-on: self-hosted

    steps:

      # --------------------------------
      # Checkout Code
      # --------------------------------
      - name: Checkout Repository
        uses: actions/checkout@v4

      # --------------------------------
      # Check Docker
      # --------------------------------
      - name: Check Docker
        shell: powershell
        run: |
          docker --version
          docker info

      # --------------------------------
      # Build Backend Image
      # --------------------------------
      - name: Build Backend Image
        shell: powershell
        run: |
          docker build `
            -t ai-smart-library-backend:latest `
            ./backend

      # --------------------------------
      # Remove Old Backend Container
      # --------------------------------
      - name: Remove Old Backend Container
        shell: powershell
        run: |
          docker rm -f smart-library-backend 2>$null
          Write-Host "Old backend container removed if it existed."

      # --------------------------------
      # Run Backend Container
      # --------------------------------
      - name: Run Backend Container
        shell: powershell
        run: |
          docker run -d `
            --name smart-library-backend `
            -p 5000:5000 `
            ai-smart-library-backend:latest

      # --------------------------------
      # Verify Backend Container
      # --------------------------------
      - name: Verify Backend Container
        shell: powershell
        run: |
          docker ps
          docker ps -f name=smart-library-backend

      # --------------------------------
      # Wait For Backend
      # --------------------------------
      - name: Wait For Backend
        shell: powershell
        run: |
          Start-Sleep -Seconds 5

      # --------------------------------
      # Backend Health Check
      # --------------------------------
      - name: Backend Health Check
        shell: powershell
        run: |
          Invoke-WebRequest `
            -Uri "http://localhost:5000/api/health" `
            -UseBasicParsing

      # --------------------------------
      # Backend Logs
      # --------------------------------
      - name: Backend Logs
        if: always()
        shell: powershell
        run: |
          docker logs smart-library-backend 2>$null